module.exports = {
    CHANGE_STATUS_SUCCESS: "Cập nhật status thành công!",
    CHANGE_STATUS_MULTI_SUCCESS: "Có %d phần tử được cập nhật status thành công!",
    CHANGE_SPECIAL_SUCCESS:"Cập nhật special thành công!",
    CHANGE_SPECIAL_MULTI_SUCCESS: "Có %d phần tử được cập nhật special thành công!",
    CHANGE_ORDERING_SUCCESS: "Cập nhật ordering thành công!",
    CHANGE_GROUP_ACP_SUCCESS: "Cập nhật group acp thành công!",
    DELETE_SUCCESS: 'Xoá phần tử thành công',
    DELETE_MULTI_SUCCESS: 'Có %d phần tử được xoá thành công',
    ADD_SUCCESS: "Thêm mới phần tử thành công",
    EDIT_SUCCESS: "Cập nhật thông tin phần tử thành công",
    ERROR_NAME: "Chiều dài từ %d đến %d kí tự",
    ERROR_ORDERING: "Phải là số nguyên lớn hơn %d và bé hơn %d",
    ERROR_STATUS: "Status phải khác rỗng",
    ERROR_SPECIAL: "Special phải khác rỗng",
    ERROR_GROUPS: "Groups phải khác rỗng",
    ERROR_GROUPACP: "Chọn giá trị cho groupACP",
    ERROR_FILE_REQUIRE: "Vui lòng chọn file upload",
    ERROR_FILE_LIMIT: "Kích thước file không phù hợp",
    ERROR_FILE_EXTENSION: "Phần mở rộng file không hợp lệ",
    ERROR_LOGIN: "Thông tin đăng nhập không chính xác",
    ERROR_PHONE: 'Phải là một giá trị khác rỗng',
};